export const GET_PRODUCTS_BYID = "GET_PRODUCTS_BYID";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const LOADING_PRODUCT = "LOADING_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const SET_FILTERS = "SET_FILTERS";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const GET_NEXT_PRODUCT_PAGE = "GET_NEXT_PRODUCT_PAGE";
